services:
  web:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./apps/web/static:/usr/share/nginx/html
      - ./apps/web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - grimoire-network

  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile.prod
    environment:
      - PYTHONPATH=/app
      - BACKEND_API_URL=http://api:8000
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - grimoire-network

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - /opt/grimoire-keeper-data/database:/data
      - /opt/grimoire-keeper-data/json:/app/data/json
    environment:
      - PYTHONPATH=/app
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - DATABASE_PATH=/data/grimoire.db
      - JSON_STORAGE_PATH=/app/data/json
    env_file:
      - .env
    depends_on:
      - weaviate
    restart: unless-stopped
    networks:
      - grimoire-network

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.1
    ports:
      - "8089:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /opt/grimoire-keeper-data/weaviate:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - grimoire-network

  elysia:
    build:
      context: .
      dockerfile: ./apps/elysia/Dockerfile
    ports:
      - "3009:3000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate
    restart: unless-stopped
    networks:
      - grimoire-network



networks:
  grimoire-network:
    driver: bridge