services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.13
    volumes:
      - ..:/workspace:cached
      - bash_history:/root
      - ~/.aws:/root/.aws:ro
    working_dir: /workspace
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
    networks:
      - grimoire-network

  bot:
    build:
      context: ../apps/bot
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/apps/bot
    environment:
      - PYTHONPATH=/workspace
      - BACKEND_API_URL=http://api:8000
    profiles:
      - production
    networks:
      - grimoire-network

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace:cached
      - sqlite_data:/data
    working_dir: /workspace/apps/api
    environment:
      - PYTHONPATH=/workspace
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - DATABASE_PATH=/data/grimoire.db
    profiles:
      - production
    networks:
      - grimoire-network

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.1
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - grimoire-network

  elysia:
    image: weaviate/elysia:latest
    ports:
      - "3009:3000"
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    depends_on:
      - weaviate
    networks:
      - grimoire-network

volumes:
  weaviate_data:
  sqlite_data:
  bash_history:

networks:
  grimoire-network:
    driver: bridge